learnDotNetCore/Models/CuisineType.cs
namespace learnDotNetCore.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        American,
        Chinese,
        Mongolian,
        German
    }
}

learnDotNetCore/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace learnDotNetCore.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name="Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

learnDotNetCore/ViewModels/HomeIndexViewModel.cs
using learnDotNetCore.Models;
using System.Collections.Generic;

namespace learnDotNetCore.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

learnDotNetCore/ViewModels/RestaurantEditModel.cs
using learnDotNetCore.Models;
using System.ComponentModel.DataAnnotations;

namespace learnDotNetCore.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

learnDotNetCore/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace learnDotNetCore.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        public string Phone()
        {
            return "5255255252";
        }

        public string Address()
        {
            return "45th st";
        }
    }
}

learnDotNetCore/Controllers/HomeController.cs
using learnDotNetCore.Models;
using learnDotNetCore.Services;
using learnDotNetCore.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace learnDotNetCore.Controllers
{
    public class HomeController : Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter)
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        public IActionResult Index()
        {
            var model = new HomeIndexViewModel();
            model.Restaurants = _restaurantData.GetAll();
            model.CurrentMessage = _greeter.GetMessageOfTheDay();

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);
            if(model == null)
            {
                RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newRestaurant = new Restaurant();
                newRestaurant.Name = model.Name;
                newRestaurant.Cuisine = model.Cuisine;

                newRestaurant = _restaurantData.Add(newRestaurant);

                return RedirectToAction(nameof(Details), new { id = newRestaurant.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

learnDotNetCore/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using learnDotNetCore.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace learnDotNetCore.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;
        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public void OnGet()
        {
            CurrentGreeting = _greeter.GetMessageOfTheDay();
        }
    }
}

learnDotNetCore/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using learnDotNetCore.Models;
using learnDotNetCore.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace learnDotNetCore.Pages
{
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);
            if(Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }
            return Page();
        }
    }
}

learnDotNetCore/ViewComponents/GreeterViewComponent.cs
using learnDotNetCore.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace learnDotNetCore.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            return View("Default",model);
        }
    }
}

learnDotNetCore/Pages/Greeting.cshtml
@page

@model GreetingModel

<div>@Model.CurrentGreeting</div>

learnDotNetCore/Pages/Restaurants/Edit.cshtml
@page "{id}"

@model EditModel

<h1>Edit</h1>
<form method="post">

    <input type="hidden" asp-for="Restaurant.Id" />

    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />

</form>

learnDotNetCore/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>
</body>
</html>

learnDotNetCore/Views/Home/Create.cshtml
@model Restaurant

@{ 
    ViewBag.Title = Model.Name;
}

<h1>Create</h1>
<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />

</form>

learnDotNetCore/Views/Home/Details.cshtml
@model Restaurant

<h1>@Model.Name</h1>
<div>@Model.Id</div>
<a asp-action="Index" asp-controller="Home">Home</a>

learnDotNetCore/Views/Home/Index.cshtml
@model learnDotNetCore.ViewModels.HomeIndexViewModel
@{
    ViewBag.Title = "Home Page";
}

<h1>All Restaurants</h1>


@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant);

}
<div>
    <a asp-action="Create">Add</a>
</div>

@section footer{
    @Model.CurrentMessage
}

learnDotNetCore/Views/Home/_Summary.cshtml
@model Restaurant

<section>
    <h3>@Model.Name</h3>
    <div>
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">Details</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

learnDotNetCore/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

learnDotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
        <vc:greeter></vc:greeter>
    </footer>
</body>
</html>